appName: themis-cluster-solution
imageVersion:
namespace: monitoring
clsuterInfo: default

#################################################################
# Application Images.
#################################################################
image:
  #repository: dockercentral.it.att.com:5100/com.att.research.ran/commscope/onecell
  ipFinderClient:
    repository: oc5g-docker-prod-suwanee.binaryrepo-east.arrisi.com/
    imagename: ipfinderclient
    version: v1.2
  prometheus:
    repository:
    imagename: prom/prometheus
    version: latest
  thanos:
    repository: quay.io/
    imagename: thanos/thanos
    version: v0.8.0
  nodeExporter:
    repository: quay.io/
    imagename: prometheus/node-exporter
    version: latest
  kubeStateMetrics:
    repository: quay.io/
    imagename: mxinden/kube-state-metrics
    version: v1.4.0-gzip.3
  addonResizer:
    repository: k8s.gcr.io/
    imagename: addon-resizer
    version: 1.8.3


ip:
  cluster: 10.53.198.176
  server: 10.53.198.190

environment:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 10s

resources:
  nodeexporter:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi
  kubestatemetrics:
    limits:
      cpu: 150m
      memory: 50Mi
    requests:
      cpu: 150m
      memory: 50Mi
storageclass:
  name: manual
  capacity: 20Gi
  hostpath: "/home/"
  resources:
    requests:
      storage: 3Gi
prometheusstore:
  nodePort: 30007
prometheusgrpc:
  nodePort: 30006

minio:
  buckettype: S3
  bucketname: themis-bucket
  access_key: minioadmin
  secret_key: minioadmin
  endpoint: 10.53.198.190:30012
  insecure: true
